/**:
  ros__parameters:
    camera_name: 'camera'
    image_width: 1280
    image_height: 720
    framerate: 30.0
    pixel_format: 'yuyv'  # Example, use your camera's format
    io_method: 'mmap'  # Options: mmap, userptr, read, dma
    video_device: '/dev/video2'  # The camera device path
