<?xml version="1.0"?>

<robot name="nav2_mobile_robot" xmlns:xacro="http://ros.org/wiki/xacro">
<xacro:include filename="$(find nav2_mobile_robot)/nav2_mobile_robot_macro.xacro" /> 

  <xacro:property name="base_radius" value="0.15" /> 
  <xacro:property name="passive_wheel_height" value="0.04" /> 
  <xacro:property name="passive_wheel_radius" value="0.025" /> 
  <xacro:property name="passive_wheel_mass" value="0.5" /> 
  <xacro:property name="wheel_radius" value="0.039" /> 
  <xacro:property name="wheel_height" value="0.02" />
  <xacro:property name="wheel_mass" value="2.5" /> 


	<link name="base_link">
		<inertial>
				<inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
			<mass value="5" />
			<origin xyz="0 0 0" />
			<cylinder_inertia  m="5" r="${base_radius}" h="0.02" />
		</inertial>    
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<cylinder length="0.02" radius="${base_radius}" />
			</geometry>
			<material name="White" />
		</visual>  
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0 " />
			<geometry>
				<cylinder length="0.02" radius="${base_radius}" />
			</geometry>
		</collision>     
	</link>
	
	<xacro:passive_wheel_joint name="passive_wheel_front_joint"
		parent="base_link"
		child="passive_wheel_front_link">
		<origin xyz="0.115 0.0 0.007" rpy="${-M_PI/2} 0 0"/>
	</xacro:passive_wheel_joint>

	<xacro:passive_wheel_link name="passive_wheel_front_link">
			<origin xyz="0 0.02 0" rpy="${M_PI/2} 0 0" />
	</xacro:passive_wheel_link>
	
	<xacro:passive_wheel_joint 
		name="passive_wheel_back_joint"
		parent="base_link"
		child="passive_wheel_back_link">
		<origin xyz="-0.135 0.0 0.009" rpy="${-M_PI/2} 0 0"/>
	</xacro:passive_wheel_joint>
	
	<xacro:passive_wheel_link
		name="passive_wheel_back_link">
			<origin xyz="0.02 0.02 0 " rpy="${M_PI/2} 0 0" /> 
	</xacro:passive_wheel_link>

	<xacro:wheel side="right" parent="base_link" translateX="0" translateY="-${base_radius}" />
	<xacro:wheel side="left" parent="base_link" translateX="0" translateY="${base_radius}" />


	<link name="lidar_link">
		 <visual>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
			  <box size="0.05 0.05 0.05" />
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
			<box size="0.05 0.05 0.05" />
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
	
	</link>

	  <joint name='lidar_sensor_joint' type='fixed'>        
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <parent link="base_link"/>

      <child link="lidar_link"/>

    </joint>


  <link name="depth_link">
    <visual>
    <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05" />
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05" />
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>

  </link>

  <joint name='depth_link_joint' type='fixed'>   	 
    <origin xyz="0 0 0.1" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="depth_link"/>
  </joint>



	  <gazebo reference="lidar_link">
        <sensor name="lidar" type='gpu_lidar'>
            <pose>0 0 0.0 0 0 0</pose>
            <topic>lidar</topic>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>640</samples>
                        <resolution>1</resolution>
                        <min_angle>-1.396263</min_angle>
                        <max_angle>1.396263</max_angle>
                    </horizontal>
                    <vertical>
                        <samples>16</samples>
                        <resolution>1</resolution>
                        <min_angle>-0.261799</min_angle>
                        <max_angle>0.261799</max_angle>
                    </vertical>
                </scan>
                <range>
                    <!-- <min>0.08</min> -->
                    <min>0.1</min>
                    <max>10.0</max>
                    <resolution>0.01</resolution>
                </range>
            </ray>
            <always_on>1</always_on>
            <visualize>true</visualize>
			<gz_frame_id>lidar_link</gz_frame_id>
            <plugin filename="libignition-gazebo-sensors-system.so" name="ignition::gazebo::systems::Sensors">
				<render_engine>ogre2</render_engine>
			</plugin>
        </sensor>
    </gazebo>

	  <gazebo reference="depth_link">
        <xacro:include filename="$(find realsense2_description)/urdf/_d435.urdf.xacro"/>
        <xacro:sensor_d435 parent="base_link" use_nominal_extrinsics="true" add_plug="false" use_mesh="true">
            <origin xyz="0 0 0.5" rpy="0 0 0"/>
        </xacro:sensor_d435>

        <sensor name="cube_camera" type="camera">
            <always_on>1</always_on>
            <update_rate>30</update_rate>
            <visualize>1</visualize>
            <pose>0 0.0175 0.5125 0 -0 0</pose>
            <topic>/camera/image_raw</topic>
            <camera name="camera">
                <horizontal_fov>1.48702</horizontal_fov>
                <image>
                    <width>1280</width>
                    <height>720</height>
                    <format>RGB_INT8</format>
                </image>
                <clip>
                    <near>0.2</near>
                    <far>10</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0</mean>
                    <stddev>0.007</stddev>
                </noise>
            </camera>
        </sensor> 

        <sensor name='d435_depth' type='depth_camera'>
            <ignition_frame_id>camera_link</ignition_frame_id>
            <always_on>1</always_on>
            <update_rate>30</update_rate>
            <visualize>1</visualize>
            <topic>/depth/image_raw</topic>
            <pose>0 0.0175 0.5125 0 -0 0</pose>
            <camera name='d435'>
                <ignition_frame_id>camera_link</ignition_frame_id>
                <horizontal_fov>1.48702</horizontal_fov>
                <image>
                    <width>1280</width>
                    <height>720</height>
                </image>
                <clip>
                    <near>0.2</near>
                    <far>10</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0</mean>
                    <stddev>0.1</stddev>
                </noise>
            </camera>
        </sensor> 
    </gazebo> 

  <gazebo>
    <plugin filename="libignition-gazebo-odometry-publisher-system" name="ignition::gazebo::systems::OdometryPublisher">
      <odom_publish_frequency>50</odom_publish_frequency>
      <odom_topic>/odom</odom_topic>
      <odom_frame>odom</odom_frame>
      <robot_base_frame>base_link</robot_base_frame>
      <tf_topic>/odom/tf</tf_topic>
    </plugin>
    </gazebo>

    <gazebo>
    <plugin
      filename="libignition-gazebo-diff-drive-system.so"
      name="ignition::gazebo::systems::DiffDrive">
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      <wheel_separation>${2*base_radius}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      
      <odom_publish_frequency>10</odom_publish_frequency>
      <topic>cmd_vel</topic>
      <robotBaseFrame>base_link</robotBaseFrame>
    </plugin>
  

    <plugin filename="libignition-gazebo-joint-state-publisher-system.so" 
        name="ignition::gazebo::systems::JointStatePublisher">
        <topic>joint_states</topic>
      </plugin>
  </gazebo>
</robot>